Repository gymnasium/gym-ui, pull requests merged in 2019-09, with the labels that each got.

#49 Bulleted list component
  package-lock.json
  src/components/BulletedList/BulletedList.tsx
  src/components/BulletedList/index.tsx
  src/components/ListItem/ListItem.tsx
  src/components/ListItem/index.tsx
  src/index.ts
  stories/BulletedList.stories.tsx
Labels: 🎛 Component

#59 Use Storybook actions
  .storybook/addons.js
  stories/Button.stories.js
  stories/GymButton.stories.tsx
  stories/index.stories.js
Labels: :star2: enhancement

#61 Feature/percy snapshot testing
  .circleci/config.yml
  .vscode/settings.json
  README.md
  package-lock.json
  package.json
Labels: :star2: enhancement

#62 Rename GymButton to Button, and set up Storybook docs
  .storybook/presets.js
  .storybook/webpack.config.js
  package-lock.json
  package.json
  src/components/Button/Button.tsx
  src/components/GymButton/GymButton.tsx
  src/components/GymButton/index.tsx
  src/index.ts
  stories/BulletedList.stories.tsx
  stories/Button.stories.tsx
  stories/Card.stories.tsx
  stories/Link.stories.tsx
  stories/TabbedContainer.stories.tsx
  stories/UserLogoutMenu.stories.tsx
Labels: :memo: documentation, :star2: enhancement

#64 Update docs for button
  src/components/Button/Button.tsx
  stories/Button.stories.tsx
Labels: :memo: docs
